workflows:
  cute-browser-ios:
    name: Cute Browser iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: CocoaPods installation
        script: |
          cd ios
          pod repo update
          pod install
      - name: Build IPA
        script: |
          # Note: Real App Store builds require code signing certificates.
          # This command builds the IPA without signing for verification.
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
